import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { startServer, root } from './serve.mjs';
import { launchBrowser } from './browser.mjs';

const output = join(root, 'docs', 'images');
await mkdir(output, { recursive: true });
const server = await startServer(); const browser = await launchBrowser();
const captured = [];
try {
  // Every frame starts in a fresh context against the checked-in demo.
  for (const [name, width, height, theme] of [['workspace', 1440, 1000, 'charcoal'], ['workspace-light', 1440, 1000, 'light'], ['mobile', 390, 844, 'charcoal']]) {
    const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 1, reducedMotion: 'reduce' });
    const page = await context.newPage(); await page.goto(server.url);
    await page.locator('#grid .tile').first().waitFor();
    await page.locator('.more-menu summary').click(); await page.getByLabel('Theme', { exact: true }).selectOption(theme); await page.locator('h1').click();
    await page.locator('#grid img, #railitems img').evaluateAll(images => {
      images.forEach(image => { image.loading = 'eager'; });
      return Promise.all(images.map(image => image.decode()));
    });
    await page.screenshot({ path: join(output, `${name}.png`) }); captured.push(`${name}.png`);
    if (name === 'workspace') {
      await page.locator('#guide-start').click(); await page.locator('#guide-card[data-step="1"]').waitFor();
      await page.screenshot({ path: join(output, 'guided-tour.png') }); captured.push('guided-tour.png');
      await page.locator('#guide-end').click();
      await page.locator('#fileinput').setInputFiles(join(root, 'tests', 'fixtures', 'grid-6x5.png'));
      await page.locator('.import-confirm:not([disabled])').waitFor();
      await page.locator('#import-review h2').click();
      await page.locator('.import-confirm').focus();
      await page.locator('#guide-hint').waitFor({ state: 'hidden' });
      await page.screenshot({ path: join(output, 'import-review.png') }); captured.push('import-review.png');
    }
    await context.close();
  }
  await writeFile(join(output, 'README.md'), '# Demo screenshots\n\nGenerated by `npm run screenshots` from the checked-in sample workspace and synthetic grid fixtures in fresh browser contexts. Only the 18 approved demo images, generated reference cards and test fixtures are used. No private saved layout or real posted photos are used.\n');
  console.log(`Captured ${captured.join(', ')}`);
} finally { await browser.close(); await server.close(); }
